// <auto-generated />
using System;
using ColmeiaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColmeiaApi.Migrations
{
    [DbContext(typeof(ColmeiaContext))]
    partial class ColmeiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ColmeiaApi.Models.Colmeia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("IdLocalizacao")
                        .HasColumnType("char(36)")
                        .HasColumnName("idLocalizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("IdLocalizacao");

                    b.ToTable("Colmeia", (string)null);
                });

            modelBuilder.Entity("ColmeiaApi.Models.Leitura", b =>
                {
                    b.Property<Guid>("IdRegistro")
                        .HasColumnType("char(36)")
                        .HasColumnName("idRegistro");

                    b.Property<Guid>("IdSensor")
                        .HasColumnType("char(36)")
                        .HasColumnName("idSensor");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(7, 3)
                        .HasColumnType("decimal(7,3)")
                        .HasColumnName("peso");

                    b.Property<decimal?>("PressaoAtmosferica")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("pressaoAtmosferica");

                    b.Property<decimal?>("TemperaturaExterna")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("temperaturaExterna");

                    b.Property<decimal?>("TemperaturaInterna")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("temperaturaInterna");

                    b.Property<decimal?>("UmidadeExterna")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("umidadeExterna");

                    b.Property<decimal?>("UmidadeInterna")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("umidadeInterna");

                    b.Property<decimal?>("VelocidadeVento")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("velocidadeVento");

                    b.HasKey("IdRegistro");

                    b.HasIndex("IdSensor");

                    b.ToTable("Leitura", (string)null);
                });

            modelBuilder.Entity("ColmeiaApi.Models.Localizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Altitude")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("altitude");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cidade");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.HasKey("Id");

                    b.ToTable("Localizacao", (string)null);
                });

            modelBuilder.Entity("ColmeiaApi.Models.Registro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Atualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("atualizacao");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criacao");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dataHoraObservacao");

                    b.Property<DateTime?>("Exclusao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("exclusao");

                    b.Property<Guid>("IdColmeia")
                        .HasColumnType("char(36)")
                        .HasColumnName("idColmeia");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("char(36)")
                        .HasColumnName("idUsuario");

                    b.HasKey("Id");

                    b.HasIndex("IdColmeia");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Registro", (string)null);
                });

            modelBuilder.Entity("ColmeiaApi.Models.Saude", b =>
                {
                    b.Property<Guid>("IdRegistro")
                        .HasColumnType("char(36)")
                        .HasColumnName("idRegistro");

                    b.Property<string>("Comida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("comida");

                    b.Property<string>("CondicaoClimatica")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("condicaoClimatica");

                    b.Property<Guid>("IdColmeia")
                        .HasColumnType("char(36)")
                        .HasColumnName("idColmeia");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext")
                        .HasColumnName("observacoes");

                    b.Property<bool>("PresencaPredador")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("presencaPredador");

                    b.Property<bool>("PresencaRainha")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("presencaRainha");

                    b.Property<bool>("Saudavel")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("saudavel");

                    b.Property<string>("TipoPredador")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipoPredador");

                    b.HasKey("IdRegistro");

                    b.HasIndex("IdColmeia");

                    b.ToTable("Saude", (string)null);
                });

            modelBuilder.Entity("ColmeiaApi.Models.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("IdColmeia")
                        .HasColumnType("char(36)")
                        .HasColumnName("idColmeia");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("IdColmeia");

                    b.ToTable("Sensor", (string)null);
                });

            modelBuilder.Entity("ColmeiaApi.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criacao");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("dataNascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Emoji")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("emoji");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("instituicao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Permissao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("permissao");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("senhaHash");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sobrenome");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ultimoLogin");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("ColmeiaApi.Models.Colmeia", b =>
                {
                    b.HasOne("ColmeiaApi.Models.Localizacao", "Localizacao")
                        .WithMany("Colmeias")
                        .HasForeignKey("IdLocalizacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localizacao");
                });

            modelBuilder.Entity("ColmeiaApi.Models.Leitura", b =>
                {
                    b.HasOne("ColmeiaApi.Models.Registro", "Registro")
                        .WithOne("Leitura")
                        .HasForeignKey("ColmeiaApi.Models.Leitura", "IdRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColmeiaApi.Models.Sensor", "Sensor")
                        .WithMany("Leituras")
                        .HasForeignKey("IdSensor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("ColmeiaApi.Models.Registro", b =>
                {
                    b.HasOne("ColmeiaApi.Models.Colmeia", "Colmeia")
                        .WithMany()
                        .HasForeignKey("IdColmeia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColmeiaApi.Models.Usuario", "Usuario")
                        .WithMany("Registros")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colmeia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ColmeiaApi.Models.Saude", b =>
                {
                    b.HasOne("ColmeiaApi.Models.Colmeia", "Colmeia")
                        .WithMany("Saudes")
                        .HasForeignKey("IdColmeia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColmeiaApi.Models.Registro", "Registro")
                        .WithOne("Saude")
                        .HasForeignKey("ColmeiaApi.Models.Saude", "IdRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colmeia");

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("ColmeiaApi.Models.Sensor", b =>
                {
                    b.HasOne("ColmeiaApi.Models.Colmeia", "Colmeia")
                        .WithMany("Sensores")
                        .HasForeignKey("IdColmeia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colmeia");
                });

            modelBuilder.Entity("ColmeiaApi.Models.Colmeia", b =>
                {
                    b.Navigation("Saudes");

                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("ColmeiaApi.Models.Localizacao", b =>
                {
                    b.Navigation("Colmeias");
                });

            modelBuilder.Entity("ColmeiaApi.Models.Registro", b =>
                {
                    b.Navigation("Leitura");

                    b.Navigation("Saude");
                });

            modelBuilder.Entity("ColmeiaApi.Models.Sensor", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("ColmeiaApi.Models.Usuario", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
